[package]
name = "monty"
version = "0.1.0"
authors = ["mental <m3nta1@yahoo.com>"]
edition = "2018"

[dependencies]
unicode-xid = "0.2.0"
cranelift = "0.51.0"
rand = "0.7.2"
libc = "0.2.66"
bitflags = "1.2.1"
lazy_static = "1.4.0"
log = "0.4.8"
serde = "1.0.103"
clap = "2.33.0"
